# Generated by Django 4.2.5 on 2023-09-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_alter_team_members_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team_members",
            name="role",
            field=models.CharField(
                choices=[
                    ("player", "Player"),
                    ("coach", "Coach"),
                    ("manager", "Manager"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Scores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(blank=True, null=True)),
                (
                    "fixture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixture",
                        to="tournament.fixtures",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_score",
                        to="tournament.teams",
                    ),
                ),
            ],
        ),
    ]
